name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  HARBOR_HOST: harbor.devops.cicd.test
  HARBOR_PROJECT: devops-platform

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | \
            docker login $HARBOR_HOST \
              -u ${{ secrets.HARBOR_USERNAME }} \
              --password-stdin

      - name: Build & Push Backend
        run: |
          docker build \
            -t $HARBOR_HOST/$HARBOR_PROJECT/backend:$SHORT_SHA \
            -t $HARBOR_HOST/$HARBOR_PROJECT/backend:latest \
            ./backend
          docker push $HARBOR_HOST/$HARBOR_PROJECT/backend:$SHORT_SHA
          docker push $HARBOR_HOST/$HARBOR_PROJECT/backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | \
            docker login $HARBOR_HOST \
              -u ${{ secrets.HARBOR_USERNAME }} \
              --password-stdin

      - name: Build & Push Frontend
        run: |
          docker build \
            -t $HARBOR_HOST/$HARBOR_PROJECT/frontend:$SHORT_SHA \
            -t $HARBOR_HOST/$HARBOR_PROJECT/frontend:latest \
            ./frontend
          docker push $HARBOR_HOST/$HARBOR_PROJECT/frontend:$SHORT_SHA
          docker push $HARBOR_HOST/$HARBOR_PROJECT/frontend:latest

  update-gitops:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Update GitOps repo
        run: |
          GITEA_HOST="gitea-http.devops-toolchain.svc.cluster.local:3000"
          DEPLOY_REPO="http://${{ secrets.GITEA_USERNAME }}:${{ secrets.GITEA_TOKEN }}@${GITEA_HOST}/${{ secrets.GITEA_USERNAME }}/devops-platform-deploy.git"

          git clone "$DEPLOY_REPO" /tmp/deploy
          cd /tmp/deploy

          # kustomization.yaml의 backend/frontend 태그 모두 업데이트
          sed -i "s|newTag: .*|newTag: \"$SHORT_SHA\"|g" kustomization.yaml

          git config user.name "gitea-ci"
          git config user.email "ci@devops.cicd.test"
          git add .
          git diff --cached --quiet || {
            git commit -m "deploy: $SHORT_SHA

          Source: $GITHUB_REPOSITORY@${GITHUB_SHA}
          By: $GITHUB_ACTOR"
            git push origin main
          }